[features]
seeds = false
[programs.localnet]
teambet = "FeF3pjJPvu2SxWYnhpDwGrRBSLy73k5aTsFv9c4PgbxQ"

[programs.devnet]
teambet = "FeF3pjJPvu2SxWYnhpDwGrRBSLy73k5aTsFv9c4PgbxQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/earth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
